app:
  build: ./compose/app/
  links:
  - redis 
  ports:
  - "5000"
  command: /usr/local/bin/gunicorn -w 2 -b :80 app:app
  env_file: .env

redis:
  image: redis

lb:
  build: ./
  links:
  - consul
  ports:
  - "80:80"

consul:
  command: -server -bootstrap -advertise 10.0.2.15
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

registrator:
  command: consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
